config/routes.rb
Rails.application.routes.draw do

  devise_for :employees, :controllers => {:registrations => "employees"}

  root 'welcome#index'
  
  resources :customers do
    collection do
      post :import
    end
  end

  resources :steps do
    collection do
      post :import
    end
  end
  
  resources :departments do
    collection do
      post :import
    end
  end
  
  resources :roles

  resources :employees do
    collection do
      post :import
    end
  end

  resources :categories do
    collection do
      post :import
    end
  end

  resources :products do
    collection do
      post :import
    end
  end

  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  require 'csv'
  
  has_ancestry
  validates_presence_of :title, :description
  has_many :products

  def self.import(file)
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      Category.create(row.to_hash)
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Title", "Description"]
      all.each do |category|
        csv << [category.title, category.description]
      end
    end
  end
end

app/models/customer.rb
require 'csv'

class Customer < ApplicationRecord

  validates_presence_of :full_name

  has_many :orders

  def full_address
    "#{address_line_1} #{city} #{state} #{country} #{zipcode}"
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      Customer.where(email: row[3]).find_or_create_by(row.to_hash)
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Full Name", "Email", "Mobile", "Full Address", "PAN Number"]
      all.each do |customer|
        csv << [customer.full_name, customer.email, customer.mobile, customer.full_address, customer.pan_number]
      end
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord

  def self.import(file)
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      Department.create(row.to_hash)
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Title"]
      all.each do |department|
        csv << [department.title]
      end
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :department
  belongs_to :role

  validates_presence_of :full_name

  def self.import(file)
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      Employee.create(row.to_hash)
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Full Name", "Email", "Department", "Role" ]
      all.each do |employee|
        csv << [employee.full_name, employee.email, employee.department.title, employee.role.title ]
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :customer

 has_many :order_products
 has_many :products, through: :order_products

 def total_amount
  products.sum(:price)
 end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_step.rb
class OrderStep < ApplicationRecord
  belongs_to :order
  belongs_to :step
end

app/models/product.rb
class Product < ApplicationRecord
  require 'csv'

  belongs_to :category

 def self.import(file)
   CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
     Product.create(row.to_hash)
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Title", "Description", "Skucode", "Price", "Category" ]
      all.each do |product|
        csv << [product.title, product.description, product.skucode, product.price, product.category.title]
      end
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/step.rb
class Step < ApplicationRecord
  require 'csv'
  
  validates_presence_of :title

  def self.import(file)
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      Step.create(row.to_hash)
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Title", "Description"]
      all.each do |step|
        csv << [step.title, step.description]
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  
  def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.csv { send_data @categories.to_csv}
    end
  end

  def create
    create!(:notice => "Great! Category has created successfully.") { categories_url }
  end

  def update
    update!(:notice => "Great! Category has updated successfully.") { categories_url }
  end

  def import
    Category.import(params[:import][:category_csv])
    redirect_to categories_path
  end

  private

    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/roles_controller.rb
class RolesController < InheritedResources::Base

  def update
    update!(:notice => "Great! Role has updated successfully.") { roles_url }
  end

  def create
    create!(:notice => "Great! Role has created successfully.") { roles_url }
  end

  private

    def role_params
      params.require(:role).permit(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.slim
= simple_form_for @category, html: { class: 'form-horizontal' } do |category|

    .form-group.row
      label.col-sm-2.col-form-label Title
      .col-sm-10
        = category.input :title, label: false, input_html: { class: 'form-control' }

    .form-group.row
      label.col-sm-2.col-form-label Description
      .col-sm-10
        = category.input :description, label: false, input_html: { class: 'form-control' }

    .form-group.row
      .col-sm-2
      .col-sm-10
        = category.submit "Update", class: 'btn btn-primary float-end'

app/views/categories/_upload_category_modal.slim
#upload_modal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"]
  .modal-dialog[role="document"]
    .modal-content
      .modal-header
        h5#exampleModalLabel.modal-title
          | Upload Categories
        button.close[type="button" data-bs-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | ×
      .modal-body

        = simple_form_for :import, url: import_categories_path, method: :post do |f|
          .grid-container
            h3 Add categories from a CSV here
            .grid-x.grid-padding-x
              .medium-6.cell
              .medium-6.cell
                = f.input :category_csv, as: :file, label: false
                = f.submit 'Import', class: 'btn btn-primary'

      .modal-footer
        button.btn.btn-primary[type="button"]
          | Save changes

app/views/categories/edit.slim
main
  .container-fluid.px-4
    h1.mt-4
      | Edit category
    ol.breadcrumb.mb-4
      li.breadcrumb-item.active
        | Home -> category -> Edit


    .card.mb-4
      .card-header
        i.fas.fa-table.me-1
        |
      .card-body= render 'categories/form'
  

app/views/categories/index.slim
main
  .row
    .col-sm-8
      .container-fluid.px-4
        h1.mt-4
          | Categories
        ol.breadcrumb.mb-4
          li.breadcrumb-item.active
            | Home -> categories

    .col-sm-1.mt-5= link_to "New", new_category_path, class: 'btn btn-primary'
    .col-sm-1.mt-5
      button.btn.btn-primary[type="button" data-bs-toggle="modal" data-bs-target="#upload_modal"] Upload
    .col-sm-1.mt-5= link_to "Download", categories_path(format: "csv"),  class: 'btn btn-primary'

    .card.mb-4
      .card-body
        table.table-striped.table-bordered.table
          thead
            tr
              th
                | Title
              th
                | Description
              th
                | Action
          tbody
            - @categories.each do |category|
              tr
                td= category.title
                td= category.description
                td
                  = link_to 'Delete', category_path(category), method: :delete, class: 'text-decoration-none'
                  = link_to 'Edit', edit_category_path(category), class: 'ml-15 text-decoration-none'

= render 'upload_category_modal'

app/views/categories/new.slim
main
  .container-fluid.px-4
    h1.mt-4
      | New category
    ol.breadcrumb.mb-4
      li.breadcrumb-item.active
        | Home -> category -> New


    .card.mb-4
      .card-header
        i.fas.fa-table.me-1
        |
      .card-body= render 'categories/form'
  